-- AutoLens AU Snowflake account bootstrap
--
-- Run this file as ACCOUNTADMIN. It is intentionally credential-free and
-- idempotent so the account configuration remains reviewable and repeatable.

USE ROLE ACCOUNTADMIN;
SET AUTOLENS_ADMIN_USER = CURRENT_USER();

-- Functional roles keep ingestion, transformation, application reads, and CI
-- isolated. AUTOLENS_PIPELINE is the runtime access role used by the scheduled
-- refresh; AUTOLENS_ADMIN owns the project containers and centralizes grants.
CREATE ROLE IF NOT EXISTS AUTOLENS_INGEST
    COMMENT = 'Writes AutoLens production raw data';
CREATE ROLE IF NOT EXISTS AUTOLENS_TRANSFORM
    COMMENT = 'Builds AutoLens production staging, core, and marts objects';
CREATE ROLE IF NOT EXISTS AUTOLENS_PIPELINE
    COMMENT = 'Scheduled AutoLens ingestion and dbt runtime role';
CREATE ROLE IF NOT EXISTS AUTOLENS_APP
    COMMENT = 'Read-only AutoLens dashboard and API role';
CREATE ROLE IF NOT EXISTS AUTOLENS_CI
    COMMENT = 'Isolated AutoLens CI build role';
CREATE ROLE IF NOT EXISTS AUTOLENS_ADMIN
    COMMENT = 'Owns and administers AutoLens Snowflake objects';

GRANT ROLE AUTOLENS_INGEST TO ROLE AUTOLENS_PIPELINE;
GRANT ROLE AUTOLENS_TRANSFORM TO ROLE AUTOLENS_PIPELINE;
GRANT ROLE AUTOLENS_PIPELINE TO ROLE AUTOLENS_ADMIN;
GRANT ROLE AUTOLENS_APP TO ROLE AUTOLENS_ADMIN;
GRANT ROLE AUTOLENS_CI TO ROLE AUTOLENS_ADMIN;
GRANT ROLE AUTOLENS_ADMIN TO ROLE SYSADMIN;

-- The human administrator can select the least-privileged role needed for a
-- task. ACCOUNTADMIN remains available but is no longer the default role.
GRANT ROLE AUTOLENS_ADMIN TO USER IDENTIFIER($AUTOLENS_ADMIN_USER);
GRANT ROLE AUTOLENS_PIPELINE TO USER IDENTIFIER($AUTOLENS_ADMIN_USER);
GRANT ROLE AUTOLENS_APP TO USER IDENTIFIER($AUTOLENS_ADMIN_USER);
GRANT ROLE AUTOLENS_CI TO USER IDENTIFIER($AUTOLENS_ADMIN_USER);

CREATE WAREHOUSE IF NOT EXISTS AUTOLENS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300
    STATEMENT_TIMEOUT_IN_SECONDS = 3600
    COMMENT = 'Cost-controlled compute for AutoLens ingestion, dbt, CI, and application reads';

-- CREATE IF NOT EXISTS preserves data. ALTER makes configuration drift
-- converge without replacing the warehouse.
ALTER WAREHOUSE AUTOLENS_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300
    STATEMENT_TIMEOUT_IN_SECONDS = 3600
    COMMENT = 'Cost-controlled compute for AutoLens ingestion, dbt, CI, and application reads';

CREATE DATABASE IF NOT EXISTS AUTOLENS_AU
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'AutoLens AU production analytics database';
CREATE TRANSIENT DATABASE IF NOT EXISTS AUTOLENS_AU_CI
    DATA_RETENTION_TIME_IN_DAYS = 0
    COMMENT = 'Isolated transient database for AutoLens CI builds';

-- PUBLIC is unused; removing it prevents accidental object creation outside
-- the explicit raw -> staging -> core/marts architecture.
DROP SCHEMA IF EXISTS AUTOLENS_AU.PUBLIC;
DROP SCHEMA IF EXISTS AUTOLENS_AU_CI.PUBLIC;

CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU.RAW WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Immutable or snapshot-preserving source-aligned production data';
CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU.STAGING WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Cleaned and standardized dbt production models';
CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU.CORE WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Conformed production facts and dimensions';
CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU.MARTS WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Application-facing production analytical marts';

CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU_CI.RAW WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 0
    COMMENT = 'CI seed and source data';
CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU_CI.STAGING WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 0
    COMMENT = 'CI staging models';
CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU_CI.CORE WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 0
    COMMENT = 'CI core models';
CREATE SCHEMA IF NOT EXISTS AUTOLENS_AU_CI.MARTS WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 0
    COMMENT = 'CI mart models';

-- Compute access. Owning AUTOLENS_ADMIN inherits all child-role access.
GRANT USAGE ON WAREHOUSE AUTOLENS_WH TO ROLE AUTOLENS_INGEST;
GRANT USAGE ON WAREHOUSE AUTOLENS_WH TO ROLE AUTOLENS_TRANSFORM;
GRANT USAGE ON WAREHOUSE AUTOLENS_WH TO ROLE AUTOLENS_APP;
GRANT USAGE ON WAREHOUSE AUTOLENS_WH TO ROLE AUTOLENS_CI;

-- Production ingestion.
GRANT USAGE ON DATABASE AUTOLENS_AU TO ROLE AUTOLENS_INGEST;
GRANT USAGE ON SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_INGEST;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_INGEST;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_INGEST;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_INGEST;

-- Production dbt transformations can read raw and build only transformed
-- schemas. They cannot create or mutate raw source tables.
GRANT USAGE ON DATABASE AUTOLENS_AU TO ROLE AUTOLENS_TRANSFORM;
GRANT USAGE ON SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_TRANSFORM;

GRANT USAGE ON SCHEMA AUTOLENS_AU.STAGING TO ROLE AUTOLENS_TRANSFORM;
GRANT USAGE ON SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_TRANSFORM;
GRANT USAGE ON SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA AUTOLENS_AU.STAGING TO ROLE AUTOLENS_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_TRANSFORM;

-- Dashboard/API access is read-only. RAW remains readable because the current
-- dashboard exposes source-health and market-monitor views directly; STAGING
-- is deliberately excluded.
GRANT USAGE ON DATABASE AUTOLENS_AU TO ROLE AUTOLENS_APP;
GRANT USAGE ON SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_APP;
GRANT USAGE ON SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_APP;
GRANT USAGE ON SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_APP;

GRANT SELECT ON ALL TABLES IN SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_APP;

-- CI is fully capable inside the transient CI database and receives no
-- production database privilege.
GRANT USAGE ON DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT CREATE SCHEMA ON DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON ALL SCHEMAS IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON FUTURE SCHEMAS IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT SELECT ON ALL VIEWS IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;
GRANT SELECT ON FUTURE VIEWS IN DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_CI;

-- Transfer container ownership last so future reruns preserve the same
-- centralized owner while existing outbound grants remain intact.
GRANT OWNERSHIP ON WAREHOUSE AUTOLENS_WH TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE AUTOLENS_AU TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE AUTOLENS_AU_CI TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU.RAW TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU.STAGING TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU.CORE TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU.MARTS TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU_CI.RAW TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU_CI.STAGING TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU_CI.CORE TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUTOLENS_AU_CI.MARTS TO ROLE AUTOLENS_ADMIN COPY CURRENT GRANTS;

ALTER USER IDENTIFIER($AUTOLENS_ADMIN_USER) SET
    DEFAULT_ROLE = AUTOLENS_ADMIN
    DEFAULT_WAREHOUSE = AUTOLENS_WH
    DEFAULT_NAMESPACE = 'AUTOLENS_AU.RAW';
